### ISSUE TITLE
Please add a rule for BRLY-2022-009

### ISSUE THREAD

**Issue by MatchPoint** [binarly-io/FwHunt#6]
In addition to BRLY-2022-009, can you add rules for all vulnerabilities that will be the topic of presentation at Black Hat 2022. Which vulnerabilities will be covered at Black Hat 2022?

**Comment by matrosov** [comment]
We release rules only after Binarly team or other parties publicly disclose related vulnerabilities and hopefully patch them properly. In respect to our responsible disclosure policies, the FwHunt rules become available to public right after our BHUSA talk at Wednesday August 10th.

**Comment by yeggor** [comment]
Rule for BRLY-2022-009 and other rules for the vulnerabilities mentioned in the BHUSA talk were released on August 10, 2022.
